version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Entered the install phase...
      - wget -qO - https://raw.githubusercontent.com/yarnpkg/releases/gh-pages/debian/pubkey.gpg | sudo apt-key add -
      - apt-get update -y
      - apt install maven
      
  pre_build:
    commands:
      - echo Entered the pre_build phase...
  #     - echo $(printenv | grep AdminBucket)
  #     - yarn install
  build:
    commands:
      - echo Entered the build phase...
      - java -versions
      - mvn -version
      # - echo Build started on 'date'
      # - yarn --version 
      # - yarn build
  post_build:
    commands:
      - echo Entered the post_build phase...
      # - aws s3 rm s3://$AdminBucket/ --recursive
      # - aws s3 sync build/ s3://$AdminBucket/ 
      # # - aws cloudfront create-invalidation --distribution-id=$DistributionId --paths '/*' 
      # - echo Build completed on 'date'
# artifacts:  
#   files:  
#     - build/**/*
